### ISSUE TITLE
MAN

### ISSUE THREAD

**Issue by quevia** [jind11/MMM-MCQA#2]
I noticed the classifier in this code is a linear classification, could you release the code of MAN classification. Thanks very much.

**Comment by jind11** [comment]
Sure, I will post the code right after the EMNLP ddl.

**Comment by quevia** [comment]
Great! Thaks a lot.

**Comment by wuyaoxuehun** [comment]
> I noticed the classifier in this code is a linear classification, could you release the code of MAN classification. Thanks very much.

Doesn't the pytorch_pretrained_bert/module/san.py file contain the MAN classifier?

**Comment by jind11** [comment]
hi, I am sorry for the late response. The class "BertForMultipleChoice_SAN2" in this line 1471 of modeling.py in pytorch_pretrained_bert folder shows how to use the MAN module (https://github.com/jind11/MMM-MCQA/blob/a4edfb035b11858f26114a7b9130e4d7eccfdce9/pytorch_pretrained_bert/modeling.py#L1471).

**Comment by quevia** [comment]
Ok, I'll check it. Thanks.

**Comment by quevia** [comment]
> hi, I am sorry for the late response. The class "BertForMultipleChoice_SAN2" in this line 1471 of modeling.py in pytorch_pretrained_bert folder shows how to use the MAN module (
> 
> https://github.com/jind11/MMM-MCQA/blob/a4edfb035b11858f26114a7b9130e4d7eccfdce9/pytorch_pretrained_bert/modeling.py#L1471
> 
> ).

Ok, I'll check it. Thanks.
